# name: str
#     model_name: str
#     endpoints: default to null
#         - api_base: str，open-source models are generally deployed with vLLM
#           api_key: str
#     api_type: str
#     tokenizer: str, the HuggingFace name of the model, which needs to be filled in for open source models.
#     parallel: int
#     max_model_len: int


gpt-4o-2024-08-06:
    model_name: gpt-4o-2024-08-06
    endpoints: 
        - api_base: 
          api_key: 
    api_type: openai
    parallel: 100


Qwen2-7B-Instruct:
    model_name: Qwen2-7B-Instruct
    endpoints:
        - api_base: http://localhost:80/v1
          api_key: EMPTY
    api_type: openai
    parallel: 100
    tokenizer: Qwen/Qwen2-7B-Instruct
    max_model_len: 32768



