name: config of answer generation for feedback-benchmark

bench_name: feedback-benchmark
test_file_name: fb_bench_dataset_v3.json

temperature: 0.0
max_tokens: 4096

# a list of model to generate answers
model_list:
  - DeepSeek-V3
