name: config of answer generation for feedback-benchmark

bench_name: feedback-benchmark
test_file_name: fb_bench_dataset.json

temperature: 0.0
max_tokens: 4096

# a list of model to generate answers
model_list:
  - Qwen2-7B-Instruct
